# Generated by Django 4.0.5 on 2022-06-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('location', models.URLField()),
            ],
        ),
    ]
